import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from './Header'
import Menu from './Menu'
import Banner from './Banner'
import Hero from './Hero'
import Blog from './Blog'
import Contact from './Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Bollo Güella</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header/>
        <Banner/>
        <Menu/>
        <Hero/>
        <Blog/>
        <Contact/>
      </main>
    </>
  )
}
